spring.application.name=licenta-tabere
#Setare port aplicatie
server.port=8080

#Baza de date configurare
spring.datasource.url=jdbc:mysql://localhost:3306/gestiune_tabere
spring.datasource.username=root
spring.datasource.password=studenta2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA configurare
spring.jpa.hibernate.ddl-auto=none
spring-jpa.show-sql=true

# Google OAuth2 Config
spring.security.oauth2.client.registration.google.client-id=820870925278-uppd51rp39j5qm6hv743fcqfh34dmdvj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

#Configurare cu eamilul CAMPCORE
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=campcore.app@gmail.com
spring.mail.password=asjrtjxiirsnofwu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.api.key=sk_test_51SVZtN2LNmOzr1lfHlyR70mlkM5MqthEtL6BzaTdxMMLOEfuxWE40LRjEX4BclbIxNwsHlgNwFX1nwJlT7twVs1400mGK9Hy4k