spring.application.name=licenta-tabere
#Setare port aplicatie
server.port=8080

#Baza de date configurare
spring.datasource.url=jdbc:mysql://localhost:3306/gestiune_tabere
spring.datasource.username=root
spring.datasource.password=studenta2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA configurare
spring.jpa.hibernate.ddl-auto=none
spring-jpa.show-sql=true